### ISSUE TITLE
Final Rig and skin for 3D modeled avatar

### ISSUE THREAD

**Issue by casierea** [casierea/ThemePark#259]
Final character Rig and Skin
![Screen Shot 2021-03-27 at 9.56.40 PM.png](https://app.gitkraken.com/api/glo/boards/5f5933fc24316d0011ed9fa8/attachments/605fff16d0f6180011b865a4)

**Comment by stevOOOOOOOOOO0** [comment]
Started Work on Rigging 3D Model

**Comment by stevOOOOOOOOOO0** [comment]
estimated time: 2 hours
actual time: 2 hours
