### ISSUE TITLE
Avatar 2nd Pass

### ISSUE THREAD

**Issue by stephensmackay** [casierea/ThemePark#272]
2nd pass at finalizing avatar. After meeting with the team, we discussed making some minor changes to  enhance the look of the avatar. 

- [x] Meeting with Stephen and Casie
- [x] Rework Model in Maya - Casie
- [x] Remodel robot torso-casie
- [x] Model buttons to add on and place-casie
- [x] uv map Robot- Casie
![opt_01_original.JPG](https://app.gitkraken.com/api/glo/boards/5f5933fc24316d0011ed9fa8/attachments/606369478ca784001249c5f2)

![opt_02_belt_buttons.JPG](https://app.gitkraken.com/api/glo/boards/5f5933fc24316d0011ed9fa8/attachments/6063694cd0f6180011b9522c)

![opt_03_Torso_bevel_buttons.JPG](https://app.gitkraken.com/api/glo/boards/5f5933fc24316d0011ed9fa8/attachments/60636952d0f6180011b95236)

![robot_02_uv_ss.JPG](https://app.gitkraken.com/api/glo/boards/5f5933fc24316d0011ed9fa8/attachments/6063d8838ca784001249e7a7)

- [x] Texture -Stephen
![ROBO8.jpg](https://app.gitkraken.com/api/glo/boards/5f5933fc24316d0011ed9fa8/attachments/60679cfc8ca78400124af689)

**Comment by stephensmackay** [comment]
Estimated time: 3 Hours

**Comment by casierea** [comment]
Casie Actual: 3 hours

**Comment by stephensmackay** [comment]
Stephen Actual:  2.5 Hours
