### ISSUE TITLE
Spawn AR Companion Dynamically in AR Space

### ISSUE THREAD

**Issue by stevOOOOOOOOOO0** [casierea/ThemePark#287]
spawn the Companion dynamically in any place after the AR has been started
- [x] Research
- [x] Script
- [x] Test in separate scene
- [x] test in main scene
![Screenshot_20210410-175304_sandbox2.jpg](https://app.gitkraken.com/api/glo/boards/5f5933fc24316d0011ed9fa8/attachments/60723b75d0f6180011bcd98b)

![Screenshot_20210410-175318_sandbox2.jpg](https://app.gitkraken.com/api/glo/boards/5f5933fc24316d0011ed9fa8/attachments/60723b7c8ca78400124d4d0e)

**Comment by stevOOOOOOOOOO0** [comment]
https://discord.com/channels/748633602711093380/749757675893555231/804521002050256907

**Comment by stephensmackay** [comment]
Estimate Time: 5 Hours

**Comment by stephensmackay** [comment]
Actual Time: 8 Hours
