### ISSUE TITLE
Issues for Marty

### ISSUE THREAD

**Issue by stevOOOOOOOOOO0** [casierea/ThemePark#319]
- [x] Back buttons for Game/Companion Scenes
- [x] Rewards for the map scene(have them in rewards but need them again
- [x] Map trail needs to be red
- [x] Ben’s 3D models in scene
- [x] Powered by trident and UVU needs to be one line
- [x] Delete menu buttons on rewards page and in main menu
- [x] Texture companion
- [x] Background main menu
- [x] Alpha behind exit
- [x] Countdown in game scene goes past Zero
- [x] Football is upside down
- [x] Raise POI’s to over the buildings
- [x] original background scene
- [x] barcode reward

**Comment by stephensmackay** [comment]
Actual Time:  6 Hours
