### ISSUE TITLE
AR Button Icon

### ISSUE THREAD

**Issue by stephensmackay** [casierea/ThemePark#322]
![ar_alt.png](https://app.gitkraken.com/api/glo/boards/5f5933fc24316d0011ed9fa8/attachments/6088cfa8d0f6180011c26e2d)

![ar_homemade.png](https://app.gitkraken.com/api/glo/boards/5f5933fc24316d0011ed9fa8/attachments/6088d1468ca784001252d947)

**Comment by casierea** [comment]
https://www.google.com/search?q=ar+icon+png+free&client=firefox-b-1-d&sxsrf=ALeKk02mimTMp1zkuLu0q5ooFTARLqWjaA:1619578684032&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiHzJbh-J_wAhVGCTQIHf1HCCwQ_AUoAXoECAEQAw&biw=1920&bih=938#imgrc=MqUY_HZiCaxUlM
